// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqbyppeyvazdmbqvqrbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxYnlwcGV5dmF6ZG1icXZxcmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODUzNTYsImV4cCI6MjA3MzI2MTM1Nn0.VzoOHadHqWj-d7rE58X3G8pYVR0hJEpFpMUn_AhEdbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});